//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary function cannot be first in the expression..
        /// </summary>
        internal static string BinaryFunctionCannotBeFirst {
            get {
                return ResourceManager.GetString("BinaryFunctionCannotBeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not render function..
        /// </summary>
        internal static string CannotRenderFunction {
            get {
                return ResourceManager.GetString("CannotRenderFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find closing brace char starting from {0} index in expression {1}..
        /// </summary>
        internal static string ClosingBraceDoesNotExist {
            get {
                return ResourceManager.GetString("ClosingBraceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator must not be zero..
        /// </summary>
        internal static string DenominatorIsZero {
            get {
                return ResourceManager.GetString("DenominatorIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression cannot be empty..
        /// </summary>
        internal static string ExpressionCannotBeEmpty {
            get {
                return ResourceManager.GetString("ExpressionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} function cannot be last in the expression..
        /// </summary>
        internal static string FunctionCannotBeLast {
            get {
                return ResourceManager.GetString("FunctionCannotBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} function cannot be only one in the expression..
        /// </summary>
        internal static string FunctionCannotBeSingle {
            get {
                return ResourceManager.GetString("FunctionCannotBeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state of semantics: when building semantic tree all nodes must be binary functions..
        /// </summary>
        internal static string InvalidSemanticsStateForTreeBuilding {
            get {
                return ResourceManager.GetString("InvalidSemanticsStateForTreeBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be {0} after {1}..
        /// </summary>
        internal static string InvalidSyntaxTokensOrder {
            get {
                return ResourceManager.GetString("InvalidSyntaxTokensOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of passed arguments does not correspond to this type of function..
        /// </summary>
        internal static string NumberOfArgumentsMismatch {
            get {
                return ResourceManager.GetString("NumberOfArgumentsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value for creating calculation object: {0}..
        /// </summary>
        internal static string UnknownCalculationObject {
            get {
                return ResourceManager.GetString("UnknownCalculationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find priority for function: {0}.
        /// </summary>
        internal static string UnknownFunctionForPrioritization {
            get {
                return ResourceManager.GetString("UnknownFunctionForPrioritization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown semantic node type: {0}..
        /// </summary>
        internal static string UnknownSemanticNodeType {
            get {
                return ResourceManager.GetString("UnknownSemanticNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown syntax token: {0}.
        /// </summary>
        internal static string UnknownSyntaxToken {
            get {
                return ResourceManager.GetString("UnknownSyntaxToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type of syntax token: {0}..
        /// </summary>
        internal static string UnknownSyntaxTokenType {
            get {
                return ResourceManager.GetString("UnknownSyntaxTokenType", resourceCulture);
            }
        }
    }
}
